#include "game.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

// Image Includes ===================================================================================
#include "images/Boss1AboutAttk.h"
#include "images/Boss1Attacking.h"
#include "images/Boss1NotAttk.h"
#include "images/Boss2AboutAttk.h"
#include "images/Boss2Attacking.h"
#include "images/Boss2NotAttk.h"
#include "images/Boss3AboutAttk.h"
#include "images/Boss3Attacking.h"
#include "images/Boss3NotAttk.h"
#include "images/Boss4AboutAttk.h"
#include "images/Boss4Attacking.h"
#include "images/Boss4NotAttk.h"
#include "images/DoorOverhead.h"
#include "images/FloorCeiling.h"
#include "images/Heart.h"
#include "images/LeftAttacking.h"
#include "images/LeftCrouching.h"
#include "images/LeftLedge.h"
#include "images/LeftMoving.h"
#include "images/LeftPlatform.h"
#include "images/Lose.h"
#include "images/RightAttacking.h"
#include "images/RightCrouching.h"
#include "images/RightLedge.h"
#include "images/RightMoving.h"
#include "images/RightPlatform.h"
#include "images/Title.h"
#include "images/Wall.h"
#include "images/Win.h"
#include "images/Instructions.h"
//===================================================================================================

// Extern variables --> in header file game.h

/* TODO: */
// Add any additional states you need for your app.
// Moved to game.h

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial game state
  GBAState state = START;

  // Load initial player states
  CurrCharacter cPlayer;
  PrevCharacter pPlayer;
  YAxisState yAxis;
  XAxisState xAxis;
  cPlayer.health = 5;
  cPlayer.row = 120;
  cPlayer.col = 110;
  cPlayer.height = 20;
  cPlayer.width = 20;
  yAxis = STANDING;
  xAxis = LEFTFACING;
  cPlayer.bossesBeaten = 0;
  int whichBossBeaten[4] = {0, 0, 0, 0};

  // Load initial jump states
  JumpState jState = DONE;
  int jumpCounter = 0;
  int jumpFrame = 10;               // Frames per jump state

  // Load initial attack states
  CurrAttackingState attackingState = NOT_ATTACKING;
  PrevAttackingState pAttackingState = NOT_ATTACKING;
  int attackCounter = 0;
  int attackFrame = 7;              // Frames per attack

  // Load initial weapon states
  CurrWeapon cPlayerWeapon;
  PrevWeapon pPlayerWeapon;
  cPlayerWeapon.height = 10;
  cPlayerWeapon.width = 10;
  cPlayerWeapon.row = 0;
  cPlayerWeapon.col = 0;
  int finishedAttacking = 0;

  // Initialize progress string
  char progress[4] = "0/4";

  // Initialize height modifier (certain values need to change based on whether crouching or standing)
  int heightModifier = 0;
  
  // Load initial boss states
  BossInfo boss;
  boss.health = 10;
  boss.row = 0;
  boss.col = 0;
  //boss.image =
  boss.height = 40;
  boss.width = 40;
  BossAttackingState bossAttacking = NOT_ATTACKING_B;
  BossDamaging damageState = MISSED;
  BossLifeState bossState = ALIVE;
  int bAttkcounter = 0;

  // Initialize boss identifier value
  int bossIdentifier = 0;

  while (1) {
    currentButtons = BUTTONS;  // Load the current state of the buttons
    pPlayer = cPlayer;         // Save current state
    pPlayerWeapon = cPlayerWeapon;

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

        // Jumping =====================================================================================================
        {
            // Jump if up is pressed
            if (KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons) && yAxis == STANDING) {
              jState = JUMPSTART;
              yAxis = JUMPING;
            }
            
            // jState changing, 40 cycles to get through the jump, 20 up 20 down
            if (yAxis == JUMPING) {
              if (jumpCounter == jumpFrame) {
                jState = MID_UP;
              } else if (jumpCounter == jumpFrame * 2) {
                jState = APEX;
              } else if (jumpCounter == jumpFrame * 3) {
                jState = MID_BOTTOM;
              } else if (jumpCounter == jumpFrame * 4) {
                jState = DONE;
              }
            }

            // jState actions
            switch (jState) {
              case JUMPSTART:
                cPlayer.row -= 4;
                jumpCounter++;
                break;

              case MID_UP:
                cPlayer.row -= 2;
                jumpCounter++;
                break;

              case APEX:
                cPlayer.row += 2;
                jumpCounter++;
                break;

              case MID_BOTTOM:
                cPlayer.row += 4;
                jumpCounter++;
                break;

              case DONE:
                if (yAxis != CROUCHING) {
                  yAxis = STANDING;
                }
                jumpCounter = 0;
                break;
            }
        }
        //==============================================================================================================

        // Horizontal Movement ===========================================================================================
        {
            // Moving left
            if (KEY_DOWN(BUTTON_LEFT, currentButtons) && yAxis != CROUCHING) {
              xAxis = LEFTFACING;
              cPlayer.col -= 2;

              if (KEY_DOWN(BUTTON_B, currentButtons)) {           // Holding B is sprinting 
                cPlayer.col -= 2;
              }
            }

            // Moving right
            if (KEY_DOWN(BUTTON_RIGHT, currentButtons) && yAxis != CROUCHING) {
              xAxis = RIGHTFACING;
              cPlayer.col += 2;

              if (KEY_DOWN(BUTTON_B, currentButtons)) {           // Holding B is sprinting 
                cPlayer.col += 2;
              }
            }
        }
        //=============================================================================================================

        // Dashing ======================================================================================================
        {
            // Dashing left
            if (KEY_JUST_PRESSED(BUTTON_L, currentButtons, previousButtons) && yAxis != CROUCHING) {
              xAxis = LEFTFACING;
              cPlayer.col -= 23;
            }

            // Dashing right
            if (KEY_JUST_PRESSED(BUTTON_R, currentButtons, previousButtons) && yAxis != CROUCHING) {
              xAxis = RIGHTFACING;
              cPlayer.col += 23;
            }
        }
        //=============================================================================================================

        // Crouching ==================================================================================================
        {
            // If DOWN is down, not mid jump, and not mid attack, charcter will crouch
            if (KEY_DOWN(BUTTON_DOWN, currentButtons) && yAxis == STANDING && attackingState == NOT_ATTACKING) {
              yAxis = CROUCHING;
              cPlayer.row += (cPlayer.height / 2);
              cPlayer.height = cPlayer.height / 2;
            }

            // When DOWN is released, character will uncrouch
            if (KEY_JUST_UNPRESSED(BUTTON_DOWN, currentButtons, previousButtons) && yAxis == CROUCHING) {
              yAxis = STANDING;
              cPlayer.height = cPlayer.height * 2;
              cPlayer.row -= (cPlayer.height / 2);
            }

            heightModifier = 20 - cPlayer.height;
        } 
        //===============================================================================================================

        // Attacking ==================================================================================================
        {
          // If not crouching, and not already attacking, pressing A attacks
          if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons) && yAxis != CROUCHING && attackingState == NOT_ATTACKING) {
            attackingState = ATTACKING;
          }

          if (attackingState == ATTACKING) {
            attackCounter++;
          }

          cPlayerWeapon.row = cPlayer.row + 5;

          if (xAxis == LEFTFACING) {
            cPlayerWeapon.col = cPlayer.col - 10;
          } else {
            cPlayerWeapon.col = cPlayer.col + 20;
          }

          if (attackCounter > attackFrame) {        // Be in ATTACKING state for five frames
              attackingState = NOT_ATTACKING;
              attackCounter = 0;
              finishedAttacking = 1;
            }
        }
        //=============================================================================================================

        // "Gravity" ====================================================================================================
        {
          // If not mid jump, will fall to simulate gravity
          if (yAxis != JUMPING) {
            cPlayer.row += 4;
          }
        }
        //===============================================================================================================

        // Progress Text ====================================================================================
        {
          // Depending on the number of bosses/statues beaten, will update amount to later display
          switch (cPlayer.bossesBeaten)
          {
          case 0:                   // Needed if game is soft reset ie SELECT is pressed
            progress[0] = '0';
            break;
          
          case 1:
            progress[0] = '1';
            break;

          case 2:
            progress[0] = '2';
            break;

          case 3:
            progress[0] = '3';
            break;

          case 4:
            progress[0] = '4';
            break;
          }
        }
        // =============================================================================================================

        // General Boss Logic ===========================================================================================
        {
          // Bosses cycle through from not attacking, to about to attack, to attacking
          if (bAttkcounter == 60) {
            bossAttacking = ABOUT_TO_B;
          } else if (bAttkcounter == 90) {
            bossAttacking = ATTACKING_B;
          } else if (bAttkcounter == 120) {
            bossAttacking = NOT_ATTACKING_B;
            damageState = MISSED;
            bAttkcounter = 0;
          }

          // if boss is in range of character's attack, boss will take damage
          if (JUST_ATTACKED(attackingState, pAttackingState) && bossState == ALIVE) {
            if (cPlayerWeapon.row >= boss.row) {
              if ((cPlayerWeapon.col > boss.col - cPlayerWeapon.width && cPlayerWeapon.col < boss.col + 20)
                  || (cPlayerWeapon.col < boss.col + boss.width && cPlayerWeapon.col > boss.col + 20)) {
                boss.health--;
              }
            }
          }

          // Updates boss state to see if player has defeated it
          if (boss.health <= 0) {
            bossState = DEAD;
          } else {
            bossState = ALIVE;
          }

          // Updates attack counter to cycle through Boss Attack Phases
          if (bossState == ALIVE) {
            bAttkcounter++;
          } else {
            bAttkcounter = 0;
            bossAttacking = NOT_ATTACKING_B;
          }
        }
        //===============================================================================================================

    switch (state) {
      case START:
      {
        // Drawing ====================================================================================
        {
          waitForVBlank();

          // Draws title screem
          drawFullScreenImageDMA(Title);
        }
        //============================================================================================

        // Next State ================================================================================
        {
          // if START is pressed, will take player to instruction
          if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
            state = INSTRUCTIONS;
          }
        }
        //==================================================================================================

        break;
      }
      case INSTRUCTIONS:
      {
        // Drawing ====================================================================================
        {
          waitForVBlank();

          // Draws title screem
          drawFullScreenImageDMA(Instructions);
        }
        //============================================================================================

        // Next State ================================================================================
        {
          // SELECT -> START
          if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            state = START;
          }

          // if START is pressed, will begin game with initialized values
          if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
            fillScreenDMA(BLACK);

            // Reinitializing player info
            cPlayer.health = 5;
            cPlayer.row = 120;
            cPlayer.col = 110;
            cPlayer.height = 20;
            cPlayer.width = 20;
            cPlayer.bossesBeaten = 0;
            yAxis = STANDING;
            xAxis = LEFTFACING;
            attackingState = NOT_ATTACKING;
            attackCounter = 0;
            jState = DONE;
            jumpCounter = 0;
            whichBossBeaten[0] = 0;
            whichBossBeaten[1] = 0;
            whichBossBeaten[2] = 0;
            whichBossBeaten[3] = 0;

            state = HUB;
          }
        }
        //==================================================================================================

        break;
      }      
      case HUB:
      {
        // Boundaries ================================================================================================
        {
          // Sets the boundaries of the main hub area
          if (cPlayer.col < 40) {
            if (cPlayer.row > 104 + heightModifier) {
              cPlayer.col = 40;
            } else if (cPlayer.row > 100 + heightModifier) {
              cPlayer.row = 100 + heightModifier;
            } else if (cPlayer.row < 80 && cPlayer.row >= 76) {
              cPlayer.row = 80;
            } else if (cPlayer.row < 76 && cPlayer.row > 44 + heightModifier) {
              cPlayer.col = 40;
            } else if (cPlayer.row > 40 + heightModifier && cPlayer.row <= 44 + heightModifier) {
              cPlayer.row = 40 + heightModifier;
            }
          } else if (cPlayer.col > 50 && cPlayer.col <= 75) {
            if (cPlayer.row < 110 && cPlayer.row >= 106) {
              cPlayer.row = 110;
            } else if (cPlayer.row < 106 && cPlayer.row > 84 + heightModifier) {
              cPlayer.col = 50;
            } else if (cPlayer.row <= 84 + heightModifier && cPlayer.row > 80 + heightModifier) {
              cPlayer.row = 80 + heightModifier;
            }
          } else if (cPlayer.col > 75 && cPlayer.col < 100) {
            if (cPlayer.row < 110 && cPlayer.row >= 106) {
              cPlayer.row = 110;
            } else if (cPlayer.row < 106 && cPlayer.row > 84 + heightModifier) {
              cPlayer.col = 100;
            } else if (cPlayer.row <= 84 + heightModifier && cPlayer.row > 80 + heightModifier) {
              cPlayer.row = 80 + heightModifier;
            }
          } else if (cPlayer.col > 120 && cPlayer.col <= 145) {
            if (cPlayer.row < 110 && cPlayer.row >= 106) {
              cPlayer.row = 110;
            } else if (cPlayer.row < 106 && cPlayer.row > 84 + heightModifier) {
              cPlayer.col = 120;
            } else if (cPlayer.row <= 84 + heightModifier && cPlayer.row > 80 + heightModifier) {
              cPlayer.row = 80 + heightModifier;
            }
          } else if (cPlayer.col > 145 && cPlayer.col < 170) {
            if (cPlayer.row < 110 && cPlayer.row >= 106) {
              cPlayer.row = 110;
            } else if (cPlayer.row < 106 && cPlayer.row > 84 + heightModifier) {
              cPlayer.col = 170;
            } else if (cPlayer.row <= 84 + heightModifier && cPlayer.row > 80 + heightModifier) {
              cPlayer.row = 80 + heightModifier;
            }
          } else if (cPlayer.col > 180) {
            if (cPlayer.row > 104 + heightModifier) {
              cPlayer.col = 180;
            } else if (cPlayer.row > 100 + heightModifier) {
              cPlayer.row = 100 + heightModifier;
            } else if (cPlayer.row < 80 && cPlayer.row >= 76) {
              cPlayer.row = 80;
            } else if (cPlayer.row < 76 && cPlayer.row > 44 + heightModifier) {
              cPlayer.col = 180;
            } else if (cPlayer.row > 40 + heightModifier && cPlayer.row <= 44 + heightModifier) {
              cPlayer.row = 40 + heightModifier;
            }
          }

          // Overall Floor
          if (cPlayer.row > 120 + heightModifier) {
            cPlayer.row = 120 + heightModifier;
          }
          
          // Overall Ceiling
          if (cPlayer.row < 20) {
            cPlayer.row = 20;
          }
        }
        // =============================================================================================================
        
        // Drawing =====================================================================================================
        {
            waitForVBlank();

            // Obstacles
            drawImageDMA(0, 0, FLOORCEILING_WIDTH, FLOORCEILING_HEIGHT, FloorCeiling);
            drawImageDMA(140, 0, FLOORCEILING_WIDTH, FLOORCEILING_HEIGHT, FloorCeiling);
            drawImageDMA(60, 0, LEFTLEDGE_WIDTH, LEFTLEDGE_HEIGHT, LeftLedge);
            drawImageDMA(120, 0, LEFTLEDGE_WIDTH, LEFTLEDGE_HEIGHT, LeftLedge);
            drawImageDMA(60, 200, RIGHTLEDGE_WIDTH, RIGHTLEDGE_HEIGHT, RightLedge);
            drawImageDMA(120, 200, RIGHTLEDGE_WIDTH, RIGHTLEDGE_HEIGHT, RightLedge);
            drawImageDMA(100, 70, LEFTPLATFORM_WIDTH, LEFTPLATFORM_HEIGHT, LeftPlatform);
            drawImageDMA(100, 140, RIGHTPLATFORM_WIDTH, RIGHTPLATFORM_HEIGHT, RightPlatform);

            // Progress text
            drawCenteredString(40, 60, 120, 20, "Statues", GRAY);
            drawCenteredString(60, 100, 40, 20, progress, GRAY);

            // Selects which character sprite to display with blacking
            switch (xAxis) {
            case LEFTFACING:
              if (attackingState == ATTACKING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayerWeapon.col, LEFTATTACKING_WIDTH, cPlayer.height, LeftAttacking);
              } else if (yAxis == CROUCHING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, LeftCrouching);
              } else {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, LeftMoving);
              }
              break;
            
            case RIGHTFACING:
              if (attackingState == ATTACKING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, RIGHTATTACKING_WIDTH, cPlayer.height, RightAttacking);
              } else if (yAxis == CROUCHING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, RightCrouching);
              } else {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, RightMoving);
              }
              break;
          }

          // Used for more blacking; w/o would leave a bit of the sword from attacking on screen
          if (finishedAttacking) {                                        // Be in ATTACKING state for five frames
            drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
            drawRectDMA(cPlayer.row, cPlayerWeapon.col, cPlayerWeapon.width, cPlayer.height, BLACK);
            finishedAttacking = 0;
          }
        }
        //===============================================================================================================

        // Next State =================================================================================================
        {
          // SELECT -> START
          if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            drawRectDMA(0, 0, 240, 160, BLACK);
            state = START;
          }

          // Sets up which boss the player will go to depending on which door they pass through
          if (cPlayer.col < 0) {
            if (cPlayer.row < 80) {
              bossIdentifier = 1;
            } else {
              bossIdentifier = 2;
            }

            drawRectDMA(0, 0, 240, 160, BLACK);
            state = HALL;
            cPlayer.col = 220;
            cPlayer.row = 120;
          }

          if (cPlayer.col > 220) {
            if (cPlayer.row < 80) {
              bossIdentifier = 3;
            } else {
              bossIdentifier = 4;
            }

            drawRectDMA(0, 0, 240, 160, BLACK);
            state = HALL;
            cPlayer.col = 0;
            cPlayer.row = 120;
          }

          if (cPlayer.bossesBeaten == 4) {
            delay(50);
            drawRectDMA(0, 0, 240, 160, BLACK);
            state = WIN;
          }
        }
        //=================================================================================================================

        break;
      }
      case HALL:
      {
        // Boundaries ===========================================================================================
        {
          // Boundaries of the hall
          if (cPlayer.col < 20) {
            if (cPlayer.row < 100 && cPlayer.row >= 96) {
              cPlayer.row = 100;
            } else if (cPlayer.row < 96) {
              cPlayer.col = 20;
            }
          } else if (cPlayer.col > 200) {
            if (cPlayer.row < 100 && cPlayer.row >= 96) {
              cPlayer.row = 100;
            } else if (cPlayer.row < 96) {
              cPlayer.col = 200;
            }
          }

          // Overall floor
          if (cPlayer.row > 120 + heightModifier) {
            cPlayer.row = 120 + heightModifier;

          }

          // Overall ceiling          
          if (cPlayer.row < 20) {
            cPlayer.row = 20;
          }
        }
        // ======================================================================================================

        // Drawing ====================================================================================================
        {
          waitForVBlank();

          // Obstacles
          drawImageDMA(0, 0, FLOORCEILING_WIDTH, FLOORCEILING_HEIGHT, FloorCeiling);
          drawImageDMA(20, 0, DOOROVERHEAD_WIDTH, DOOROVERHEAD_HEIGHT, DoorOverhead);
          drawImageDMA(140, 0, FLOORCEILING_WIDTH, FLOORCEILING_HEIGHT, FloorCeiling);
          drawImageDMA(20, 220, DOOROVERHEAD_WIDTH, DOOROVERHEAD_HEIGHT, DoorOverhead);

          // Same as HUB's, will be notated as "Sprite"
          switch (xAxis) {
            case LEFTFACING:
              if (attackingState == ATTACKING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayerWeapon.col, LEFTATTACKING_WIDTH, cPlayer.height, LeftAttacking);
              } else if (yAxis == CROUCHING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, LeftCrouching);
              } else {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, LeftMoving);
              }
              break;
            
            case RIGHTFACING:
              if (attackingState == ATTACKING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, RIGHTATTACKING_WIDTH, cPlayer.height, RightAttacking);
              } else if (yAxis == CROUCHING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, RightCrouching);
              } else {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, RightMoving);
              }
              break;
          }

          if (finishedAttacking) {
            drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
            drawRectDMA(cPlayer.row, cPlayerWeapon.col, cPlayerWeapon.width, cPlayer.height, BLACK);
            finishedAttacking = 0;
          }
        }
        //================================================================================================================

        // Next State ================================================================================================
        {
          // SELECT -> START
          if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            drawRectDMA(0, 0, 240, 160, BLACK);
            state = START;
          }
          
          // Sets up the boss data depending on which door player had entered HALL from
          // Also may send player back to HUB depending on the door
          if (cPlayer.col < 0) {
            if (bossIdentifier == 1) {
              drawRectDMA(0, 0, 240, 160, BLACK);
              state = BOSS1;
              cPlayer.col = 220;
              cPlayer.row = 120;

              // Boss 1 States
              if (!whichBossBeaten[0]) {
                boss.health = 10;
              } else {
                boss.health = 0;
              }

              boss.row = 100;
              boss.col = 60;
              boss.height = 40;
              boss.width = 40;
              bossAttacking = NOT_ATTACKING_B;
            }

            if (bossIdentifier == 2) {
              drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
              state = BOSS2;
              cPlayer.col = 220;
              cPlayer.row = 120;

              // Boss 2 States
              if (!whichBossBeaten[1]) {
                boss.health = 10;
              } else {
                boss.health = 0;
              }

              boss.row = 100;
              boss.col = 20;
              boss.height = 40;
              boss.width = 40;
              bossAttacking = NOT_ATTACKING_B;
            }

            if (bossIdentifier == 3) {
              drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
              state = HUB;
              cPlayer.col = 220;
              cPlayer.row = 40;
            }

            if (bossIdentifier == 4) {
              drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
              state = HUB;
              cPlayer.col = 220;
              cPlayer.row = 100;
            }
          }

          if (cPlayer.col > 220) {
            if (bossIdentifier == 1) {
              drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
              state = HUB;
              cPlayer.col = 0;
              cPlayer.row = 40;
            }

            if (bossIdentifier == 2) {
              drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
              state = HUB;
              cPlayer.col = 0;
              cPlayer.row = 100;
            }

            if (bossIdentifier == 3) {
              drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
              state = BOSS3;
              cPlayer.col = 0;
              cPlayer.row = 120;

              // Boss 3 States
              if (!whichBossBeaten[2]) {
                boss.health = 10;
              } else {
                boss.health = 0;
              }

              boss.row = 100;
              boss.col = 140;
              boss.height = 40;
              boss.width = 40;
              bossAttacking = NOT_ATTACKING_B;
            }

            if (bossIdentifier == 4) {
              drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
              state = BOSS4;
              cPlayer.col = 0;
              cPlayer.row = 120;

              // Boss 4 States
              if (!whichBossBeaten[3]) {
                boss.health = 10;
              } else {
                boss.health = 0;
              }

              boss.row = 100;
              boss.col = 180;
              boss.height = 40;
              boss.width = 40;
              bossAttacking = NOT_ATTACKING_B;
            }
          }
        }
        //==========================================================================================================

        break;
      }
      case BOSS1:           // Top left
      {
        // Boundaries ===========================================================================================
        {
          if (cPlayer.col < 20) {
            cPlayer.col = 20;
          } else if (cPlayer.col > 40 && cPlayer.col <= 70) {
            if (cPlayer.row > 84 + heightModifier) {
              cPlayer.col = 40;
            } else if (cPlayer.row <= 84 + heightModifier && cPlayer.row > 80) {
              cPlayer.row = 80 + heightModifier;
            }
          } else if (cPlayer.col > 70 && cPlayer.col < 100) {
            if (cPlayer.row > 84 + heightModifier) {
              cPlayer.col = 100;
            } else if (cPlayer.row <= 84 + heightModifier && cPlayer.row > 80) {
              cPlayer.row = 80 + heightModifier;
            }
          } else if (cPlayer.col > 200) {
            if (cPlayer.row < 100 && cPlayer.row >= 96) {
              cPlayer.row = 100;
            } else if (cPlayer.row < 96) {
              cPlayer.col = 200;
            }
          }

          if (cPlayer.row > 120 + heightModifier) {                            // Overall floor
            cPlayer.row = 120 + heightModifier;

          }
          
          if (cPlayer.row < 20) {                          // Overall ceiling
            cPlayer.row = 20;
          }
        }
        // ======================================================================================================

        // Boss 1 Logic ===============================================================================================
        {
          // If boss is alive, and attacking then player is damaged
          // damageState is to prevent double jeopardy for standing in the way of the same attack
          if (bossAttacking == ATTACKING_B && damageState == MISSED && bossState == ALIVE) {
            if (cPlayer.row >= 80) {
              if (cPlayer.col > 20 && cPlayer.col < 120) {
                cPlayer.health--;
                damageState = HIT;
              }
            }
          }

          // If boss dies, update the num of bosses (for progress) and for ensuring boss stays dead
          if (bossState == DEAD && whichBossBeaten[0] == 0) {
            cPlayer.bossesBeaten++;
            whichBossBeaten[0] = 1;
          }
        }
        //=============================================================================================================

        // Drawing ====================================================================================================
        {
          waitForVBlank();

          // Obstacles
          drawImageDMA(0, 0, FLOORCEILING_WIDTH, FLOORCEILING_HEIGHT, FloorCeiling);
          drawImageDMA(20, 0, WALL_WIDTH, WALL_HEIGHT, Wall);
          drawImageDMA(140, 0, FLOORCEILING_WIDTH, FLOORCEILING_HEIGHT, FloorCeiling);
          drawImageDMA(20, 220, DOOROVERHEAD_WIDTH, DOOROVERHEAD_HEIGHT, DoorOverhead);

          // Boss Statue and its multiple states
          if (bossState == ALIVE) {
            switch (bossAttacking) {
              case NOT_ATTACKING_B:
                drawRectDMA(boss.row - 20, boss.col - 20, BOSS1ATTACKING_WIDTH, BOSS1ATTACKING_HEIGHT, BLACK);
                drawImageDMA(boss.row, boss.col, boss.width, boss.height, Boss1NotAttk);
                break;
              case ABOUT_TO_B:
                drawImageDMA(boss.row, boss.col, boss.width, boss.height, Boss1AboutAttk);
                break;
              case ATTACKING_B:
                drawImageDMA(boss.row - 20, boss.col - 20, BOSS1ATTACKING_WIDTH, BOSS1ATTACKING_HEIGHT, Boss1Attacking);
                break;
            }
          } else {
            drawRectDMA(boss.row - 20, boss.col - 20, BOSS1ATTACKING_WIDTH, BOSS1ATTACKING_HEIGHT, BLACK);
            drawRectDMA(boss.row, boss.col, boss.width, boss.height, BLACK);
          }

          // Sprite
          switch (xAxis) {
            case LEFTFACING:
              if (attackingState == ATTACKING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayerWeapon.col, LEFTATTACKING_WIDTH, cPlayer.height, LeftAttacking);
              } else if (yAxis == CROUCHING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, LeftCrouching);
              } else {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, LeftMoving);
              }
              break;
            
            case RIGHTFACING:
              if (attackingState == ATTACKING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, RIGHTATTACKING_WIDTH, cPlayer.height, RightAttacking);
              } else if (yAxis == CROUCHING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, RightCrouching);
              } else {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, RightMoving);
              }
              break;
          }

          if (finishedAttacking) {                                        // Be in ATTACKING state for five frames
            drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
            drawRectDMA(cPlayer.row, cPlayerWeapon.col, cPlayerWeapon.width, cPlayer.height, BLACK);
            finishedAttacking = 0;
          }
        }
        //================================================================================================================

        // Next State =================================================================================================
        {
          // SELECT -> START
          if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            drawRectDMA(0, 0, 240, 160, BLACK);
            state = START;
          }

          // Door back to HALL
          if (cPlayer.col > 220) {
            drawRectDMA(0, 0, 240, 160, BLACK);
            state = HALL;
            cPlayer.col = 0;
            cPlayer.row = 120;
          }

          // If the boss dies, send back to HUB
          if (bossState == DEAD) {
            drawCenteredString(40, 80, 80, 20, "Statue 1 Defeated", WHITE);
            delay(50);
            drawRectDMA(0, 0, 240, 160, BLACK);
            state = HUB;
            attackingState = NOT_ATTACKING;
            cPlayer.row = 120;
            cPlayer.col = 110;
            cPlayer.health++;
          }

          // If health goes to 0, game over
          if (cPlayer.health == 0) {
            delay(50);
            drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
            state = LOSE;
          }
        }
        //=================================================================================================================

        break;
      }
      case BOSS2:           // Bottom left; No comments, essentially same as BOSS 1
      {
        // Boundaries ===========================================================================================
        {
          if (cPlayer.col < 20) {
            if (cPlayer.row <= 84 && cPlayer.row > 80) {
              cPlayer.row = 80;
            }
            cPlayer.col = 20;
          } else if (cPlayer.col < 60) {
            if (cPlayer.row > 84 + heightModifier) {
              cPlayer.col = 60;
            } else if (cPlayer.row <= 84 + heightModifier && cPlayer.row > 80) {
              cPlayer.row = 80 + heightModifier;
            }
          } else if (cPlayer.col > 200) {
            if (cPlayer.row < 100 && cPlayer.row >= 96) {
              cPlayer.row = 100;
            } else if (cPlayer.row < 96) {
              cPlayer.col = 200;
            }
          }

          if (cPlayer.row > 120 +  heightModifier) {                            // Overall floor
            cPlayer.row = 120 + heightModifier;

          }
          
          if (cPlayer.row < 20) {                          // Overall ceiling
            cPlayer.row = 20;
          }
        }
        // ======================================================================================================

        // Boss 2 Logic ===============================================================================================
        {
          if (bossAttacking == ATTACKING_B && damageState == MISSED && bossState == ALIVE) {
            if (cPlayer.row >= 110 && cPlayer.row < 130) {
              if (cPlayer.col >= 60 && cPlayer.col < 100) {
                cPlayer.health--;
                damageState = HIT;
              }
            }
          }

          if (bossState == DEAD && whichBossBeaten[1] == 0) {
            cPlayer.bossesBeaten++;
            whichBossBeaten[1] = 1;
          }
        }
        //=============================================================================================================

        // Drawing ====================================================================================================
        {
          waitForVBlank();

          // Obstacles
          drawImageDMA(0, 0, FLOORCEILING_WIDTH, FLOORCEILING_HEIGHT, FloorCeiling);
          drawImageDMA(20, 0, WALL_WIDTH, WALL_HEIGHT, Wall);
          drawImageDMA(140, 0, FLOORCEILING_WIDTH, FLOORCEILING_HEIGHT, FloorCeiling);
          drawImageDMA(20, 220, DOOROVERHEAD_WIDTH, DOOROVERHEAD_HEIGHT, DoorOverhead);

          // Boss Statue
          if (bossState == ALIVE) {
            switch (bossAttacking) {
              case NOT_ATTACKING_B:
                drawRectDMA(boss.row, boss.col, BOSS2ATTACKING_WIDTH, BOSS2ATTACKING_HEIGHT, BLACK);
                drawImageDMA(boss.row, boss.col, boss.width, boss.height, Boss2NotAttk);
                break;
              case ABOUT_TO_B:
                drawImageDMA(boss.row, boss.col, boss.width, boss.height, Boss2AboutAttk);
                break;
              case ATTACKING_B:
                drawImageDMA(boss.row, boss.col, BOSS2ATTACKING_WIDTH, BOSS2ATTACKING_HEIGHT, Boss2Attacking);
                break;
            }
          } else {
            drawRectDMA(boss.row, boss.col, BOSS2ATTACKING_WIDTH, BOSS2ATTACKING_HEIGHT, BLACK);
            drawRectDMA(boss.row, boss.col, boss.width, boss.height, BLACK);
          }

          switch (xAxis) {
            case LEFTFACING:
              if (attackingState == ATTACKING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayerWeapon.col, LEFTATTACKING_WIDTH, cPlayer.height, LeftAttacking);
              } else if (yAxis == CROUCHING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, LeftCrouching);
              } else {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, LeftMoving);
              }
              break;
            
            case RIGHTFACING:
              if (attackingState == ATTACKING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, RIGHTATTACKING_WIDTH, cPlayer.height, RightAttacking);
              } else if (yAxis == CROUCHING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, RightCrouching);
              } else {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, RightMoving);
              }
              break;
          }

          if (finishedAttacking) {                                        // Be in ATTACKING state for five frames
            drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
            drawRectDMA(cPlayer.row, cPlayerWeapon.col, cPlayerWeapon.width, cPlayer.height, BLACK);
            finishedAttacking = 0;
          }
        }
        //================================================================================================================

        // Next State =================================================================================================
        {
          if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
            state = START;
          }

          if (cPlayer.col > 220) {
            drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
            state = HALL;
            cPlayer.col = 0;
            cPlayer.row = 120;
          }

          if (bossState == DEAD) {
            drawCenteredString(40, 80, 80, 20, "Statue 2 Defeated", WHITE);
            delay(50);
            drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change to "Boss 2 defeated" after background image
            state = HUB;
            attackingState = NOT_ATTACKING;
            cPlayer.row = 120;
            cPlayer.col = 110;
            cPlayer.health++;
          }

          if (cPlayer.health == 0) {
            delay(50);
            drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
            state = LOSE;
          }
        }
        //=================================================================================================================

        break;
      }
      case BOSS3:           // Top right; No comments, essentially same as BOSS 1
      {
        // Boundaries ===========================================================================================
        {
          if (cPlayer.col < 20) {
            if (cPlayer.row < 100 && cPlayer.row >= 96) {
              cPlayer.row = 100;
            } else if (cPlayer.row < 96) {
              cPlayer.col = 20;
            }
          } else if (cPlayer.col > 120 && cPlayer.col <= 150) {
            if (cPlayer.row > 84 + heightModifier) {
              cPlayer.col = 120;
            } else if (cPlayer.row <= 84 + heightModifier && cPlayer.row > 80) {
              cPlayer.row = 80 + heightModifier;
            }
          } else if (cPlayer.col > 150 && cPlayer.col < 180) {
            if (cPlayer.row > 84 + heightModifier) {
              cPlayer.col = 180;
            } else if (cPlayer.row <= 84 + heightModifier && cPlayer.row > 80) {
              cPlayer.row = 80 + heightModifier;
            }
          } else if (cPlayer.col > 200) {
            cPlayer.col = 200;
          }

          if (cPlayer.row > 120 + heightModifier) {                            // Overall floor
            cPlayer.row = 120 + heightModifier;

          }
          
          if (cPlayer.row < 20) {                          // Overall ceiling
            cPlayer.row = 20;
          }
        }
        // ======================================================================================================

        // Boss 3 Logic ===============================================================================================
        {
          if (bossAttacking == ATTACKING_B && damageState == MISSED && bossState == ALIVE) {
            if (cPlayer.row >= 80) {
              if (cPlayer.col > 100 && cPlayer.col < 200) {
                cPlayer.health--;
                damageState = HIT;
              }
            }
          }

          if (bossState == DEAD && whichBossBeaten[2] == 0) {
            cPlayer.bossesBeaten++;
            whichBossBeaten[2] = 1;
          }
        }
        //=============================================================================================================

        // Drawing ====================================================================================================
        {
          waitForVBlank();

          // Obstacles
          drawImageDMA(0, 0, FLOORCEILING_WIDTH, FLOORCEILING_HEIGHT, FloorCeiling);
          drawImageDMA(20, 220, WALL_WIDTH, WALL_HEIGHT, Wall);
          drawImageDMA(140, 0, FLOORCEILING_WIDTH, FLOORCEILING_HEIGHT, FloorCeiling);
          drawImageDMA(20, 0, DOOROVERHEAD_WIDTH, DOOROVERHEAD_HEIGHT, DoorOverhead);

          // Boss Statue
          if (bossState == ALIVE) {
            switch (bossAttacking) {
              case NOT_ATTACKING_B:
                drawRectDMA(boss.row - 20, boss.col - 20, BOSS3ATTACKING_WIDTH, BOSS3ATTACKING_HEIGHT, BLACK);
                drawImageDMA(boss.row, boss.col, boss.width, boss.height, Boss3NotAttk);
                break;
              case ABOUT_TO_B:
                drawImageDMA(boss.row, boss.col, boss.width, boss.height, Boss3AboutAttk);
                break;
              case ATTACKING_B:
                drawImageDMA(boss.row - 20, boss.col - 20, BOSS3ATTACKING_WIDTH, BOSS3ATTACKING_HEIGHT, Boss3Attacking);
                break;
            }
          } else {
            drawRectDMA(boss.row - 20, boss.col - 20, BOSS3ATTACKING_WIDTH, BOSS3ATTACKING_HEIGHT, BLACK);
            drawRectDMA(boss.row, boss.col, boss.width, boss.height, BLACK);
          }

          switch (xAxis) {
            case LEFTFACING:
              if (attackingState == ATTACKING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayerWeapon.col, LEFTATTACKING_WIDTH, cPlayer.height, LeftAttacking);
              } else if (yAxis == CROUCHING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, LeftCrouching);
              } else {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, LeftMoving);
              }
              break;
            
            case RIGHTFACING:
              if (attackingState == ATTACKING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, RIGHTATTACKING_WIDTH, cPlayer.height, RightAttacking);
              } else if (yAxis == CROUCHING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, RightCrouching);
              } else {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, RightMoving);
              }
              break;
            }

            if (finishedAttacking) {                                        // Be in ATTACKING state for five frames
              drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
              drawRectDMA(cPlayer.row, cPlayerWeapon.col, cPlayerWeapon.width, cPlayer.height, BLACK);
              finishedAttacking = 0;
            }
        }
        //================================================================================================================

        // Next State =================================================================================================
        {
          if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
            state = START;
          }

          if (cPlayer.col < 0) {
            drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
            state = HALL;
            cPlayer.col = 220;
            cPlayer.row = 120;
          }

          if (bossState == DEAD) {
            drawCenteredString(40, 80, 80, 20, "Statue 3 Defeated", WHITE);
            delay(50);
            drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change to "Boss 3 defeated" after background image
            state = HUB;
            attackingState = NOT_ATTACKING;
            cPlayer.row = 120;
            cPlayer.col = 110;
            cPlayer.health++;
          }

          if (cPlayer.health == 0) {
            delay(50);
            drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
            state = LOSE;
          }
        }
        //=================================================================================================================

        break;
      }
      case BOSS4:           // Bottom left; No comments, essentially same as BOSS 1
      {
        // Boundaries ===========================================================================================
        {
          if (cPlayer.col < 20) {
            if (cPlayer.row < 100 && cPlayer.row >= 96) {
              cPlayer.row = 100;
            } else if (cPlayer.row < 96) {
              cPlayer.col = 20;
            }
          } else if (cPlayer.col > 160 && cPlayer.col <= 200) {
            if (cPlayer.row > 84 + heightModifier) {
              cPlayer.col = 160;
            } else if (cPlayer.row <= 84 + heightModifier && cPlayer.row > 80) {
              cPlayer.row = 80 + heightModifier;
            }
          } else if (cPlayer.col > 200) {
            if (cPlayer.row <= 84 && cPlayer.row > 80) {
              cPlayer.row = 80;
            }
            cPlayer.col = 200;
          }

          if (cPlayer.row > 120 +  heightModifier) {                            // Overall floor
            cPlayer.row = 120 + heightModifier;

          }
          
          if (cPlayer.row < 20) {                          // Overall ceiling
            cPlayer.row = 20;
          }
        }
        // ======================================================================================================

        // Boss 4 Logic ===============================================================================================
        {
          if (bossAttacking == ATTACKING_B && damageState == MISSED && bossState == ALIVE) {
            if (cPlayer.row >= 110 && cPlayer.row < 130) {
              if (cPlayer.col > 120 && cPlayer.col <= 160) {
                cPlayer.health--;
                damageState = HIT;
              }
            }
          }

          if (bossState == DEAD && whichBossBeaten[3] == 0) {
            cPlayer.bossesBeaten++;
            whichBossBeaten[3] = 1;
          }
        }
        //=============================================================================================================

        // Drawing ====================================================================================================
        {
          waitForVBlank();

          // Obstacles
          drawImageDMA(0, 0, FLOORCEILING_WIDTH, FLOORCEILING_HEIGHT, FloorCeiling);
          drawImageDMA(20, 220, WALL_WIDTH, WALL_HEIGHT, Wall);
          drawImageDMA(140, 0, FLOORCEILING_WIDTH, FLOORCEILING_HEIGHT, FloorCeiling);
          drawImageDMA(20, 0, DOOROVERHEAD_WIDTH, DOOROVERHEAD_HEIGHT, DoorOverhead);

          // Boss Statue
          if (bossState == ALIVE) {
            switch (bossAttacking) {
              case NOT_ATTACKING_B:
                drawRectDMA(boss.row, boss.col - 40, BOSS4ATTACKING_WIDTH, BOSS4ATTACKING_HEIGHT, BLACK);
                drawImageDMA(boss.row, boss.col, boss.width, boss.height, Boss4NotAttk);
                break;
              case ABOUT_TO_B:
                drawImageDMA(boss.row, boss.col, boss.width, boss.height, Boss4AboutAttk);
                break;
              case ATTACKING_B:
                drawImageDMA(boss.row, boss.col - 40, BOSS4ATTACKING_WIDTH, BOSS4ATTACKING_HEIGHT, Boss4Attacking);
                break;
            }
          } else {
            drawRectDMA(boss.row, boss.col - 40, BOSS4ATTACKING_WIDTH, BOSS4ATTACKING_HEIGHT, BLACK);
            drawRectDMA(boss.row, boss.col, boss.width, boss.height, BLACK);
          }

          switch (xAxis) {
            case LEFTFACING:
              if (attackingState == ATTACKING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayerWeapon.col, LEFTATTACKING_WIDTH, cPlayer.height, LeftAttacking);
              } else if (yAxis == CROUCHING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, LeftCrouching);
              } else {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, LeftMoving);
              }
              break;
            
            case RIGHTFACING:
              if (attackingState == ATTACKING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, RIGHTATTACKING_WIDTH, cPlayer.height, RightAttacking);
              } else if (yAxis == CROUCHING) {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, RightCrouching);
              } else {
                drawRectDMA(pPlayer.row, pPlayer.col, pPlayer.width, pPlayer.height, BLACK);
                drawImageDMA(cPlayer.row, cPlayer.col, cPlayer.width, cPlayer.height, RightMoving);
              }
              break;
          }

          if (finishedAttacking) {                                        // Be in ATTACKING state for five frames
            drawRectDMA(pPlayer.row, pPlayerWeapon.col, pPlayerWeapon.width, pPlayer.height, BLACK);
            drawRectDMA(cPlayer.row, cPlayerWeapon.col, cPlayerWeapon.width, cPlayer.height, BLACK);
            finishedAttacking = 0;
          }
        }
        //================================================================================================================

        // Next State =================================================================================================
        {
          if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
            state = START;
          }

          if (cPlayer.col < 0) {
            drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
            state = HALL;
            cPlayer.col = 220;
            cPlayer.row = 120;
          }

          if (bossState == DEAD) {
            drawCenteredString(40, 80, 80, 20, "Statue 4 Defeated", WHITE);
            delay(50);
            drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change to "Boss 2 defeated" after background image
            state = HUB;
            attackingState = NOT_ATTACKING;
            cPlayer.row = 120;
            cPlayer.col = 110;
            cPlayer.health++;
          }

          if (cPlayer.health == 0) {
            delay(50);
            drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
            state = LOSE;
          }
        }
        //=================================================================================================================

        break;
      }
      case WIN:
      {
        // Drawing ====================================================================================
        {
          waitForVBlank();

          // Displays win screen
          drawFullScreenImageDMA(Win);
        }
        //============================================================================================
        
        // Next State =================================================================================
        {
          // SELECT -> START
          if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
            state = START;
          }
        }
        //===============================================================================================

        break;
      }
      case LOSE:
      {
        // Drawing ===============================================================================================================
        {
          waitForVBlank();

          // Displays Game Over Screen
          drawFullScreenImageDMA(Lose);
        }
        // =======================================================================================================================

        // Next State ==========================================================================================================
        {
          // SELECT -> START
          if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            drawRectDMA(0, 0, 240, 160, BLACK);              // Temp, change after background image
            state = START;
          }
        }
        //=================================================================================================================

        break;
      }
    }

    // Displays amount of hearts left
    if (state != START && state != WIN && state != LOSE && state != INSTRUCTIONS) {
      for (int i = 0; i < cPlayer.health; i++) {
        drawImageDMA(145, 5 + (20 * i), 10, 10, Heart);
      }
    }
    

    previousButtons = currentButtons;  // Store the current state of the buttons
    pAttackingState = attackingState;
  }

  return 0;
}

// Delays running by about n tenths of a second
void delay(int n) {
  volatile int x = 0;
  for(int i=0; i<n*8000; i++) {
    x++;
  }
}